version: '3' 

services: 
  frontend:  
    image: frontend
    build:
      context: ../../part1/1.12/frontend
    environment:
      - API_URL=http://localhost/api

  backend:  
    image: backend
    build:
      context: ../../part1/1.12/backend
    environment: 
      - FRONT_URL=http://localhost/
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=pass
      - DB_HOST=db
    depends_on:
      - redis
      - db

  redis:
    image: redis 

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend