version: '3' 

services: 
  frontend:  
    image: frontend
    build:
      context: ../../part1/1.12/frontend
    ports: 
      - 5000:5000

  backend:  
    image: backend
    build:
      context: ../../part1/1.12/backend
    ports: 
      - 8000:8000
    environment: 
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=pass
      - DB_HOST=db
    depends_on:
      - redis
      - db

  redis:
    image: redis 

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass

volumes:
  pgdata:
     external: true