version: '3' 

services: 
  frontend:  
    image: frontend
    build:
      context: ../../part1/1.12/frontend
    ports: 
      - 5000:5000

  backend:  
    image: backend
    build:
      context: ../../part1/1.12/backend
    ports: 
      - 8000:8000